pfapp/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views



app_name="pfapp"
urlpatterns = [
    path("",views.Get_started.as_view(),name="Get_started"),
    path("register/",views.Register.as_view(),name="register"),
    path("accounts/login/", views.UpdatedLoginView.as_view(extra_context={"leftclass":"d-none d-md-block"})),
    path("dashboard/",views.Dashboard.as_view(),name="dashboard"),
    path("submit_profile/",views.Profile.as_view(),name="submit_profile"),
    path("submit_project/",views.Project.as_view(),name="submit_project"),
    path("submit_work/",views.Work.as_view(),name="submit_work"),
    path("portfolio_api/",views.PortfolioAPI.as_view(),name="portfolio"),
    path("portfolio_api_with_img/",views.APIViewSet.as_view({'get': 'list'}),name="api"),
    path("logout/",views.logout_view,name="logout"),

]

portflikr_proj/urls.py
from django.contrib import admin
from django.contrib.auth import urls 
from django.urls import path,include
from django.conf import settings  # new
from django.urls import path, include  # new
from django.conf.urls.static import static


urlpatterns = [
    path("",include("pfapp.urls")),
    path('admin/', admin.site.urls),
    path("accounts/",include(urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pfapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Person(models.Model):
    img = models.ImageField(upload_to = "images/",null=True)
    img1 = models.ImageField(upload_to = "images/",null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE) 
    linkedin = models.URLField(blank=True)
    github = models.URLField(blank=True)
    occupation = models.CharField(max_length=30,blank=True)
    skills = models.CharField(max_length=255,blank=True)
    hobbies = models.CharField(max_length=255,blank=True)
    desc = models.TextField(blank=True)
    def __str__(self):
        return self.user.first_name
    

class Projects(models.Model):
    project_name = models.CharField(max_length=30)
    url = models.URLField(blank=True)
    desc = models.TextField(blank=True)
    person = models.ForeignKey('Person',related_name='projects_set', on_delete=models.CASCADE) 
    def __str__(self):
        return self.project_name
    
class Work(models.Model):
    role = models.CharField(max_length=50)
    company = models.CharField(max_length=50)
    desc = models.TextField(blank=True)
    start_date=models.DateField(blank=True,null=True)
    end_date=models.DateField(blank=True,null=True)
    person = models.ForeignKey('Person',related_name='work_set', on_delete=models.CASCADE) 
    def __str__(self):
        return (self.role+" : "+self.company)

pfapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.forms import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit,Layout
from django.urls import reverse_lazy
from .models import Person,Projects,Work




class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ("first_name","last_name","username", "email", "password1", "password2")
    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
                
        self.helper.form_show_labels=True
        self.helper.form_method = 'post'
        self.helper.form_action = reverse_lazy('projURLS:index')
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.layout = Layout(
                "username",
                'email',
                "password1", "password2",
        )
        self.helper.add_input(Submit('submit', 'Register'))



# class DashboardForm(forms.Form):
#     occupation = forms.CharField(label="Occupation",max_length=30,required=False)
#     project_name = forms.CharField(label="Project name",max_length=30,required=False)
#     url = forms.URLField(label="URL for the project",required=False)
#     desc = forms.CharField(label="Description",required=False)


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False)


class DashboardFormUser(ModelForm):
    class Meta:
        model = User
        fields = ["first_name","last_name","username", "email"]

class DashboardFormPersonal(ModelForm):
    class Meta:
        model = Person
        fields=['desc','hobbies','github','linkedin','occupation','skills','img','img1']


class DashboardFormProjects(ModelForm):
    class Meta:
        model = Projects
        exclude=['person']

class DashboardFormWork(ModelForm):
    class Meta:
        model = Work
        exclude=['start_date','end_date','person']

pfapp/views.py
from django.shortcuts import render,redirect
from django.views import View
from .forms import NewUserForm,LoginForm,DashboardFormPersonal,DashboardFormProjects,DashboardFormUser, DashboardFormWork
from django.contrib.auth import login,logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Person,Projects
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import HttpResponseNotFound
from rest_framework import permissions,viewsets
from rest_framework.parsers import MultiPartParser, FormParser
from .serializer import Personserializer


# from . serializer import *

# Get Started Page.
class Get_started(View):                                 
    def get(self, request) :
        ctx={}
        ctx['rightclass']="d-none d-md-block"
        return render(request,'pfapp/Get_started.html',ctx)


# Register VIEW
class Register(View):
    def get(self,request):
        form = NewUserForm()
        note=request.session.get('note',0)
        if (note):
            del(request.session['note'])
        return render (request=request, template_name="registration/register.html",context={"register_form":form,"leftclass":"d-none d-md-block","note":note})
    
    def post(self,request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            user_info = User.objects.get(username=user)
            person_info=Person(user=user_info)
            person_info.save()


            login(request, user)
            messages.success(request, "Registration successful." )
            
            return redirect("pfapp:dashboard")
        print(form.cleaned_data)
        # print("Error")
        request.session['note'] = 1
        return redirect(request.path)
    
# DASHBOARD VIEW
class Dashboard(LoginRequiredMixin,View):                                 
    def get(self, request) :
        #FORMS

        user_form=DashboardFormUser()
        personal_form=DashboardFormPersonal()
        projects_form=DashboardFormProjects()
        work_form=DashboardFormWork()

        #Information
        user_info=User.objects.get(username=request.user)
        projects=user_info.person.projects_set.all()
        workexp=user_info.person.work_set.all()

        ctx={'user_form':user_form,"personal_form":personal_form,'projects_form':projects_form,'work_form':work_form,"user":user_info,"projects":projects,"works":workexp}
        return render(request,'pfapp/dashboard.html',ctx)
    
    def post(self,request):
        #Portfolio Call
        if (request.POST.get('portfolio-style')!=None):
            # return HttpResponseNotFound("Still in development coming soon")
            # return redirect("http://localhost:3000")
            return redirect("https://portflikr.web.app/"+str(request.POST.get('portfolio-style'))+"/"+str(request.user.pk-1))

 

class Profile(View):
    def post(self,request):
        #Forms and cleaning
        form1=DashboardFormUser(request.POST, request.FILES)
        form2=DashboardFormPersonal(request.POST, request.FILES)
        print(form2)
        form1.is_valid()
        form2.is_valid()
        cleaned1=form1.cleaned_data
        cleaned2=form2.cleaned_data

        # print("In Profile View ")
        # print(cleaned1)
        # print(cleaned2)

        # Handling Data
        print(cleaned2)
        if 'img' in cleaned2:
            request.user.person.img=cleaned2['img']
        if 'img1' in cleaned2:
            request.user.person.img1=cleaned2['img1']
        request.user.first_name=cleaned1['first_name']
        request.user.last_name=cleaned1['last_name']
        request.user.email=cleaned1['email']
        if 'username' in cleaned1:
            request.user.username=cleaned1['username']
        request.user.person.occupation=cleaned2['occupation']
        request.user.person.skills=cleaned2['skills']
        request.user.person.hobbies=cleaned2['hobbies']
        if (cleaned2['desc']!=''): 
                request.user.person.desc=cleaned2['desc']
        if ('linkedin' in cleaned2):
            request.user.person.linkedin=cleaned2['linkedin']
        else:
            messages.error(request, "Invalid URL entered before")
        if ('github' in cleaned2):
            request.user.person.github=cleaned2['github']
        else:
            messages.error(request, "Invalid URL entered before")
        request.user.person.save()
        request.user.save()

        return redirect(reverse_lazy("pfapp:dashboard"))   



class Project(View):
    def post(self,request):
        pid=request.POST.get('projectID')

        #Deleting The project
        if (request.POST.get('btn--delete') and pid!="-1"):
            request.user.person.projects_set.get(pk=pid).delete()
            return redirect(reverse_lazy("pfapp:dashboard"))

        #Handling Data
        form3=DashboardFormProjects(request.POST)
        form3.is_valid()
        cleaned3=form3.cleaned_data
        # print("In project view")
        # print(cleaned3)

        #Old project
        if (pid!="new"):
            projid=request.user.person.projects_set.get(pk=pid)
            # print(projid)
            projid.project_name=cleaned3['project_name']
            if ('url' in cleaned3):
                projid.url=cleaned3['url']
            else:
                messages.error(request, "Invalid URL entered before")
            if (cleaned3['desc']!=''): 
                projid.desc=cleaned3['desc']
            projid.save()
        #New Project
        else:
            if ('url' not in cleaned3):
                messages.error(request, "Invalid URL entered before")
            else:
                request.user.person.projects_set.create(project_name=cleaned3['project_name'],url=cleaned3['url'],desc=cleaned3['desc'])    
        return redirect(reverse_lazy("pfapp:dashboard"))


class Work(View):
    def post(self,request):
        workid=request.POST.get('workID')

        #Deletion
        if (request.POST.get('btn--delete') and workid!="-1"):
            request.user.person.work_set.get(pk=workid).delete()
            return redirect(reverse_lazy("pfapp:dashboard"))
        

        #Handling Data
        form4=DashboardFormWork(request.POST)
        form4.is_valid()
        cleaned4=form4.cleaned_data

        #New work
        if (workid=="new"):
            print(cleaned4)
            request.user.person.work_set.create(role=cleaned4['role'],company=cleaned4['company'],desc=cleaned4['desc'])
        #Old Work
        else:
            # print(cleaned4)
            wid=request.user.person.work_set.get(pk=workid)
            # print(wid)
            wid.role=cleaned4['role']
            wid.company=cleaned4['company']
            if (cleaned4['desc']!=''): 
                wid.desc=cleaned4['desc']
            wid.save()

        return redirect(reverse_lazy("pfapp:dashboard"))



#LOGOUT PAGE 
def logout_view(request):
    logout(request)
    messages.success(request,"Logged out successfully.")
    return redirect(reverse_lazy('pfapp:Get_started'))


# PORTFOLIO VIEW

class PortfolioAPI(APIView):
    # serializer_class = ReactSerializer
    def get(self, request):
        output_list = [{
                    "first_name":output.user.first_name,
                    "last_name":output.user.last_name,
                    "username":output.user.username,
                    "email":output.user.email,
                    "skills": output.skills, 
                    "hobbies": output.hobbies, 
                    "occupation": output.occupation,
                    "github":output.github,
                    "linkedin":output.linkedin,
                    "aboutme":output.desc,
                    "projects":[
                        {
                            "name":x.project_name,
                            "url":x.url,
                            "desc":x.desc
                        }
                            for x in output.projects_set.all()
                    ],
                    "work_exp":[
                        {
                            "role":x.role,
                            "company":x.company,
                            "desc":x.desc
                        }
                            for x in output.work_set.all()
                    ]
                }
            for output in Person.objects.all()]
        return Response(output_list)

    # def post(self, request):

    #     serializer = ReactSerializer(data=request.data)
    #     if serializer.is_valid(raise_exception=True):
    #         serializer.save()
    #         return Response(serializer.data)

class APIViewSet(viewsets.ModelViewSet):
    queryset = Person.objects.order_by('id')
    serializer_class = Personserializer
    parser_classes = (MultiPartParser, FormParser)
    permission_classes = [
        permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)


# LOGIN VIEW
class UpdatedLoginView(LoginView):
    form_class = LoginForm
        
    def form_valid(self, form):
        remember_me = form.cleaned_data['remember_me']  # get remember me data from cleaned_data of form
        # print(remember_me)
        if not remember_me:
            self.request.session.set_expiry(0)  # if remember me is 
            self.request.session.modified = True
        else:   
            self.request.session.set_expiry(1209600)
        return super(UpdatedLoginView, self).form_valid(form)
    



#DEPRECIATED

       #Deleting a work exp or project
        # pid=request.POST.get('projectID')
        # workid=request.POST.get('workID')
        # if (request.POST.get('btn--delete') and pid!="-1"):

pfapp/templates/pfapp/Get_started.html
{% extends "pfapp/base.html" %}
{% load static %}

{% block title %}
    Generate your portfolio
{% endblock %}

{% block head %}
    <link href="{% static 'pfapp/css/getstarted_style.css' %}" rel="stylesheet">
    {% include 'pfapp/messages.html' %}
{% endblock %}

{% block leftside %}
    <div class="display-4 GS container-fluid text-center">
        Get Started
    </div>
    <div class="desc container text-center">
        From concept to reality, build your dream
        portfolio website that effortlessly showcases
        your skills and leaves a lasting digital
        footprint
    </div>
    <div class="text-center container-fluid">
        {% if user.is_authenticated %}
            <a class="loginbtn" href="{% url 'pfapp:dashboard' %}"> Go to Dashboard <br></a>       
        {% else %} 
            <a class="loginbtn" href="{% url 'login' %}?next={% url 'pfapp:dashboard' %}"> Login </a>
        {%endif%}
    </div>
    
    <div class="text-center container-fluid">
        <a href="{%  url 'pfapp:register' %}?next={% url 'pfapp:dashboard' %}" class="regbtn">Register</a>
    </div>
    
    
{% endblock %}


{% block rightside %}
    <div class="img1 container-fluid text-center">
        <img id="img1id" src="{% static 'pfapp/img/img1.png' %}">
    </div>
{% endblock %}

pfapp/templates/pfapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
    {% load static %}
    <title>{% block title %}  <!--title goes here-->  {% endblock %}| Portflikr </title>
    <!--Bootstrap CSS-->
    {%block head%} {%endblock%}
    <link href="{% static 'pfapp/css/base_style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alice&family=Inter:wght@300&family=Montserrat:wght@700&family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'pfapp/img/logo.png' %}" >
    <link rel="icon" type="image/x-icon" href="{% static 'pfapp/img/logo.png' %}">
</head>


<body>
    {%block messages%} {%endblock%}
    <div class="mainrow row fill-height" >
        <div class="{{leftclass}} left containter-fluid  col-md-6 ">
            <p class="logo_title"><img src="{% static 'pfapp/img/logo.png' %}" height="40px" style="padding-bottom:1%;">PortFlikr</p> 
            {%block leftside%} {%endblock%}
        </div>
        <div class="{{rightclass}} right containter-fluid right col-md-6 ">
            {%block rightside%} {%endblock%}
            <div class="container-fluid text-center my_name">
                Made by Aritro Ghosh @ NITCS
            </div>
        </div>
    </div>
    <div id="loading">
        <img id="loading-image" src="{% static 'pfapp/img/spinner.svg'%}" alt="Loading..." />
    </div>
    <!-- Optional Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script>
        $(window).on('load', function () {
                $('#loading').hide();
            }) 
    </script>
</body>



</html>

pfapp/templates/pfapp/messages.html
{% for message in messages %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="margin: 0%;">
    {{ message }}
    <button type="button" class="close btn btn-outline-secondary" data-bs-dismiss="alert" aria-label="Close" style="float:right; --bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
      <span aria-hidden="True">X</span>
    </button>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
{% endfor %}

pfapp/templates/pfapp/portfolio.html
{% extends "pfapp/base.html" %}

{% block head %}
    {% include 'pfapp/messages.html' %}
{% endblock %}


{% block title %}
    Portfolio
{% endblock %}


{% block rightside %}
    PORTFOLIO PAGE for {{user}}
    {{user.first_name}}
    {{user.last_name}}
    {{user.email}}
    {{user.person.occupation}}
{% endblock %}